pub const State = enum {
    doctype,
    tag_start,
    tag_name,
    tag_body,
    tag_end,
    prolog_body,
    prolog_end,
    tag_attr_key_q,
    tag_attr_key,
    tag_attr_value_q,
    tag_attr_value,
    closing_tag_start,
    self_closing_tag,
    content,
    comment_q,
    comment_body,
};

pub const Tag = enum {
    invalid,
    prolog_open,
    prolog_end,
    doctype,
    tag_open,
    tag_close,
    self_closing_tag,
    attr_key,
    attr_value,
    content,
    comment,
    eof,
};
